# Generated by Django 5.2 on 2025-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
