# Generated by Django 5.2 on 2025-06-22 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_basket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('customer_address', models.CharField(max_length=200, verbose_name='Адрес клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные')], default='card', max_length=10, verbose_name='Способ оплаты')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('shipped', 'Отправлен'), ('completed', 'Выполнен')], default='in_progress', max_length=20, verbose_name='Статус заказа')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend_api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
